spring:
  h2:
    console.enabled: true
  datasource:
    # url: jdbc:h2:mem:testdb
    url: jdbc:h2:file:~/highscoreh2db;DB_CLOSE_ON_EXIT=FALSE;IFEXISTS=FALSE;DB_CLOSE_DELAY=-1;MVCC=TRUE
    username: sa
    password: 
    
    name: highscoreh2db
    driverClassName: org.h2.Driver
    initialize: false

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update
    show-sql: true
    properties.hibernate.format_sql: true